#!/bin/bash

echo "🔍 MongoDB Atlas集群状态诊断"
echo "================================"

echo ""
echo "📋 错误分析："
echo "从最新日志可以看到："
echo "- 错误类型: ReplicaSetNoPrimary"
echo "- 集群名称: atlas-126eq3-shard-0"
echo "- 服务器前缀: ac-dopjson-shard-00-*"
echo "- 原服务器前缀: ac-dopjson-shard-00-*"
echo ""

echo "🎯 问题诊断："
echo "1. MongoDB Atlas集群可能正在重启或维护"
echo "2. 集群配置可能发生了变化"
echo "3. 需要检查集群状态和连接字符串"
echo ""

echo "🔧 解决方案："
echo ""
echo "方案1: 检查MongoDB Atlas集群状态"
echo "- 登录 https://cloud.mongodb.com/"
echo "- 检查集群是否正常运行"
echo "- 查看集群状态指示器"
echo ""

echo "方案2: 重新获取连接字符串"
echo "- 在MongoDB Atlas中点击 'Connect'"
echo "- 选择 'Connect your application'"
echo "- 复制新的连接字符串"
echo "- 更新腾讯云函数环境变量"
echo ""

echo "方案3: 尝试不同的连接参数"
echo "当前URI: mongodb+srv://admin:UeVOSuzgZ4glfKBV@cluster0.b4d7wmh.mongodb.net/"
echo ""
echo "建议尝试的URI格式："
echo "1. 添加重试参数:"
echo "   mongodb+srv://admin:UeVOSuzgZ4glfKBV@cluster0.b4d7wmh.mongodb.net/?retryWrites=true&w=majority"
echo ""
echo "2. 添加超时参数:"
echo "   mongodb+srv://admin:UeVOSuzgZ4glfKBV@cluster0.b4d7wmh.mongodb.net/?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000"
echo ""
echo "3. 完整参数版本:"
echo "   mongodb+srv://admin:UeVOSuzgZ4glfKBV@cluster0.b4d7wmh.mongodb.net/?retryWrites=true&w=majority&serverSelectionTimeoutMS=5000"
echo ""

echo "🧪 测试当前连接..."
echo "正在测试MongoDB连接..."

# 测试当前连接
curl -s -X GET "https://service-4ej5ggqj-1259648581.gz.apigw.tencentcs.com/health" | jq . 2>/dev/null || echo "连接测试失败"

echo ""
echo "📝 下一步操作建议："
echo "1. 首先检查MongoDB Atlas集群状态"
echo "2. 如果集群正常，尝试更新连接字符串"
echo "3. 在腾讯云函数中更新MONGODB_URI环境变量"
echo "4. 等待2-3分钟后重新测试"
echo ""

echo "⚠️  重要提示："
echo "ReplicaSetNoPrimary错误通常表示："
echo "- 集群正在选举新的主节点"
echo "- 集群正在维护或重启"
echo "- 网络连接问题"
echo "- 连接字符串过期"