#!/bin/bash

echo "🚀 腾讯云函数紧急重新部署脚本"
echo "================================"
echo "📅 执行时间: $(date)"
echo ""

echo "📋 当前状态分析:"
echo "✅ 本地MongoDB连接: 完全正常"
echo "✅ 网络环境: 已优化"
echo "❌ 腾讯云函数: 无响应（状态码000）"
echo ""

echo "🔧 解决方案: 重新部署腾讯云函数"
echo "==============================="
echo ""

echo "📦 使用修复版部署包:"
echo "inventory-scf-fixed-20250729-120946.zip"
echo ""

echo "🎯 部署步骤:"
echo "1. 登录腾讯云控制台"
echo "   https://console.cloud.tencent.com/scf"
echo ""
echo "2. 进入云函数服务"
echo "   选择地域: 广州"
echo "   找到函数: inventory-api"
echo ""
echo "3. 重新部署代码"
echo "   - 点击 '函数代码'"
echo "   - 选择 '上传zip包'"
echo "   - 上传文件: inventory-scf-fixed-20250729-120946.zip"
echo "   - 点击 '保存'"
echo ""
echo "4. 配置环境变量"
echo "   - 点击 '函数配置'"
echo "   - 找到 '环境变量'"
echo "   - 设置以下变量:"
echo ""
echo "   MONGODB_URI=mongodb+srv://admin:UeVOSuzgZ4glfKBV@cluster0.b4d7wmh.mongodb.net/?serverSelectionTimeoutMS=10000&connectTimeoutMS=15000"
echo "   JWT_SECRET=your-secret-key-2024"
echo "   NODE_ENV=production"
echo ""
echo "5. 保存配置"
echo "   - 点击 '保存'"
echo "   - 等待部署完成（约1-2分钟）"
echo ""

echo "🧪 部署后验证:"
echo "=============="
echo "等待部署完成后，运行以下命令验证:"
echo ""
echo "cd /Users/suizhihao/Trae/ke && ./verify-mongodb-connection.sh"
echo ""

echo "📊 预期结果:"
echo "============"
echo "✅ 状态码: 200"
echo "✅ 响应: {\"success\":true,\"message\":\"数据库连接正常\"}"
echo ""

echo "⚠️  重要提示:"
echo "============"
echo "1. 确保上传的是 inventory-scf-fixed-20250729-120946.zip"
echo "2. 环境变量必须完全按照上述格式设置"
echo "3. 保存后等待1-2分钟让配置生效"
echo "4. 如果仍有问题，可能需要删除函数重新创建"
echo ""

echo "🔗 相关文件:"
echo "==========="
echo "- 部署包: ./edge-functions/scf-deploy/inventory-scf-fixed-20250729-120946.zip"
echo "- 验证脚本: ./verify-mongodb-connection.sh"
echo "- 详细指南: ./腾讯云函数代码修复部署指南.md"
echo ""

echo "📞 如需帮助:"
echo "==========="
echo "如果部署后仍有问题，请检查:"
echo "1. 腾讯云函数日志"
echo "2. MongoDB Atlas集群状态"
echo "3. 网络连接状态"
echo ""

echo "🏁 脚本完成时间: $(date)"